### ISSUE TITLE
Custom Icons Feature

### ISSUE THREAD

**Issue by TRaMeLL** [Aldaviva/KeePassTrayIconLockState#2]
Hello, it would be nice to be able to customize icons.
![customicons01](https://github.com/Aldaviva/KeePassTrayIconLockState/assets/10239461/558627b0-9c3d-4401-982b-1200789b69e9)

**Comment by Aldaviva** [comment]
Here's an [experimental build](https://github.com/Aldaviva/KeePassTrayIconLockState/files/12436438/KeePassTrayIconLockState-customicons.zip) that reads `.ico` files from the plugin DLL's directory to allow custom icons. There are 6 icon files it will search for. Any icon it can't find an external file for will fall back to the existing built-in icons.
- `opening-darktaskbar.ico`
- `opening-lighttaskbar.ico`
- `open-darktaskbar.ico`
- `open-lighttaskbar.ico`
- `closed-darktaskbar.ico`
- `closed-lighttaskbar.ico`

It's using ICO files instead of easier to deal with PNGs so that it can support multiple resolutions on high-DPI displays. On a normal density display, it will use the 16×16px image in the icon, and on a high density display (e.g. 200% scaling factor) it will use 32×32px. If you need to convert images to ICO format, there are several free tools that you can use; I used [Iconaton](https://sourceforge.net/projects/iconaton/files/iconaton/Iconaton%200.1%20Beta%201/).

This includes some of the custom icons you uploaded. I didn't include the closed icon because the plugin hides the icon from the notification area when the database is closed or locked.

![screenshot](https://github.com/Aldaviva/KeePassTrayIconLockState/assets/1417794/a207f3fb-df14-4d2f-8edd-97d31b9a7a08)

Let me know if this works for you.

**Comment by TRaMeLL** [comment]
Thanks! It works perfectly for me.

**Comment by Aldaviva** [comment]
Released in [1.2.0](https://github.com/Aldaviva/KeePassTrayIconLockState/releases/tag/1.2.0).
